module MessageTypes
	CHECK_IN = 'check-in'
	CHECK_OUT = 'check-out'
	RSVP = 'rsvp'
	MESSAGE = 'check-out'
	CONFIRMATION = 'confirmation'
  NEIGHBORS_INVITATION = 'neighbor-invitation'
  ACCEPT_NEIGHBORS_INVITATION = 'accept-neighbor-invitation'
  CANCEL_NEIGHBORS_INVITATION = 'cancel-neighbor-invitation'
  DECLINE_NEIGHBORS_INVITATION = 'decline-neighbor-invitation'
  PLAY_INVITATION = 'play-invitation'
  ACCEPT_PLAY_INVITATION = 'accept-play-invitation'
  CANCEL_PLAY_INVITATION = 'cancel-play-invitation'
  DECLINE_PLAY_INVITATION = 'decline-play-invitation'
end
