module PlayceletLightingModes
  SHINING = '01'
  SLOW_FLASHING = '0A'
  MEDIUM_FLASHING = '14'
  RAPID_FLASHING = '32'
  PLAY_INVITATION_RECEIVED = SHINING
  PLAY_INVITATION_NOTIFICATION_FOR_AUTHOR_AT_HOME = SHINING
  PLAY_INVITATION_NOTIFICATION_FOR_INVITED_AT_HOME = SHINING
  PLAY_INVITATION_NOTIFICATION_FOR_AUTHOR_AT_HOME_RSVP = RAPID_FLASHING
  PLAY_INVITATION_NOTIFICATION_FOR_INVITED_AT_HOME_RSVP = SHINING
  PLAY_INVITATION_NOTIFICATION_FOR_INVITED_SOMEWHERE_ELSE = SLOW_FLASHING
  PLAY_INVITATION_NOTIFICATION_RSVP = RAPID_FLASHING
  PLAY_INVITATION_NOTIFICATION_CAME = SHINING
  PLAY_INVITATION_NOTIFICATION_DUE_HOME = RAPID_FLASHING
  PLAY_INVITATION_NOTIFICATION_COME_HOME = RAPID_FLASHING
end
