require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NeighborsInvitationsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # NeighborsInvitation. As you add validations to NeighborsInvitation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NeighborsInvitationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all neighbors_invitations as @neighbors_invitations" do
      neighbors_invitation = NeighborsInvitation.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:neighbors_invitations)).to eq([neighbors_invitation])
    end
  end

  describe "GET show" do
    it "assigns the requested neighbors_invitation as @neighbors_invitation" do
      neighbors_invitation = NeighborsInvitation.create! valid_attributes
      get :show, {:id => neighbors_invitation.to_param}, valid_session
      expect(assigns(:neighbors_invitation)).to eq(neighbors_invitation)
    end
  end

  describe "GET new" do
    it "assigns a new neighbors_invitation as @neighbors_invitation" do
      get :new, {}, valid_session
      expect(assigns(:neighbors_invitation)).to be_a_new(NeighborsInvitation)
    end
  end

  describe "GET edit" do
    it "assigns the requested neighbors_invitation as @neighbors_invitation" do
      neighbors_invitation = NeighborsInvitation.create! valid_attributes
      get :edit, {:id => neighbors_invitation.to_param}, valid_session
      expect(assigns(:neighbors_invitation)).to eq(neighbors_invitation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NeighborsInvitation" do
        expect {
          post :create, {:neighbors_invitation => valid_attributes}, valid_session
        }.to change(NeighborsInvitation, :count).by(1)
      end

      it "assigns a newly created neighbors_invitation as @neighbors_invitation" do
        post :create, {:neighbors_invitation => valid_attributes}, valid_session
        expect(assigns(:neighbors_invitation)).to be_a(NeighborsInvitation)
        expect(assigns(:neighbors_invitation)).to be_persisted
      end

      it "redirects to the created neighbors_invitation" do
        post :create, {:neighbors_invitation => valid_attributes}, valid_session
        expect(response).to redirect_to(NeighborsInvitation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved neighbors_invitation as @neighbors_invitation" do
        post :create, {:neighbors_invitation => invalid_attributes}, valid_session
        expect(assigns(:neighbors_invitation)).to be_a_new(NeighborsInvitation)
      end

      it "re-renders the 'new' template" do
        post :create, {:neighbors_invitation => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested neighbors_invitation" do
        neighbors_invitation = NeighborsInvitation.create! valid_attributes
        put :update, {:id => neighbors_invitation.to_param, :neighbors_invitation => new_attributes}, valid_session
        neighbors_invitation.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested neighbors_invitation as @neighbors_invitation" do
        neighbors_invitation = NeighborsInvitation.create! valid_attributes
        put :update, {:id => neighbors_invitation.to_param, :neighbors_invitation => valid_attributes}, valid_session
        expect(assigns(:neighbors_invitation)).to eq(neighbors_invitation)
      end

      it "redirects to the neighbors_invitation" do
        neighbors_invitation = NeighborsInvitation.create! valid_attributes
        put :update, {:id => neighbors_invitation.to_param, :neighbors_invitation => valid_attributes}, valid_session
        expect(response).to redirect_to(neighbors_invitation)
      end
    end

    describe "with invalid params" do
      it "assigns the neighbors_invitation as @neighbors_invitation" do
        neighbors_invitation = NeighborsInvitation.create! valid_attributes
        put :update, {:id => neighbors_invitation.to_param, :neighbors_invitation => invalid_attributes}, valid_session
        expect(assigns(:neighbors_invitation)).to eq(neighbors_invitation)
      end

      it "re-renders the 'edit' template" do
        neighbors_invitation = NeighborsInvitation.create! valid_attributes
        put :update, {:id => neighbors_invitation.to_param, :neighbors_invitation => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested neighbors_invitation" do
      neighbors_invitation = NeighborsInvitation.create! valid_attributes
      expect {
        delete :destroy, {:id => neighbors_invitation.to_param}, valid_session
      }.to change(NeighborsInvitation, :count).by(-1)
    end

    it "redirects to the neighbors_invitations list" do
      neighbors_invitation = NeighborsInvitation.create! valid_attributes
      delete :destroy, {:id => neighbors_invitation.to_param}, valid_session
      expect(response).to redirect_to(neighbors_invitations_url)
    end
  end

end
