require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SupervisorsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Supervisor. As you add validations to Supervisor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SupervisorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all supervisors as @supervisors" do
      supervisor = Supervisor.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:supervisors)).to eq([supervisor])
    end
  end

  describe "GET show" do
    it "assigns the requested supervisor as @supervisor" do
      supervisor = Supervisor.create! valid_attributes
      get :show, {:id => supervisor.to_param}, valid_session
      expect(assigns(:supervisor)).to eq(supervisor)
    end
  end

  describe "GET new" do
    it "assigns a new supervisor as @supervisor" do
      get :new, {}, valid_session
      expect(assigns(:supervisor)).to be_a_new(Supervisor)
    end
  end

  describe "GET edit" do
    it "assigns the requested supervisor as @supervisor" do
      supervisor = Supervisor.create! valid_attributes
      get :edit, {:id => supervisor.to_param}, valid_session
      expect(assigns(:supervisor)).to eq(supervisor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Supervisor" do
        expect {
          post :create, {:supervisor => valid_attributes}, valid_session
        }.to change(Supervisor, :count).by(1)
      end

      it "assigns a newly created supervisor as @supervisor" do
        post :create, {:supervisor => valid_attributes}, valid_session
        expect(assigns(:supervisor)).to be_a(Supervisor)
        expect(assigns(:supervisor)).to be_persisted
      end

      it "redirects to the created supervisor" do
        post :create, {:supervisor => valid_attributes}, valid_session
        expect(response).to redirect_to(Supervisor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved supervisor as @supervisor" do
        post :create, {:supervisor => invalid_attributes}, valid_session
        expect(assigns(:supervisor)).to be_a_new(Supervisor)
      end

      it "re-renders the 'new' template" do
        post :create, {:supervisor => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested supervisor" do
        supervisor = Supervisor.create! valid_attributes
        put :update, {:id => supervisor.to_param, :supervisor => new_attributes}, valid_session
        supervisor.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested supervisor as @supervisor" do
        supervisor = Supervisor.create! valid_attributes
        put :update, {:id => supervisor.to_param, :supervisor => valid_attributes}, valid_session
        expect(assigns(:supervisor)).to eq(supervisor)
      end

      it "redirects to the supervisor" do
        supervisor = Supervisor.create! valid_attributes
        put :update, {:id => supervisor.to_param, :supervisor => valid_attributes}, valid_session
        expect(response).to redirect_to(supervisor)
      end
    end

    describe "with invalid params" do
      it "assigns the supervisor as @supervisor" do
        supervisor = Supervisor.create! valid_attributes
        put :update, {:id => supervisor.to_param, :supervisor => invalid_attributes}, valid_session
        expect(assigns(:supervisor)).to eq(supervisor)
      end

      it "re-renders the 'edit' template" do
        supervisor = Supervisor.create! valid_attributes
        put :update, {:id => supervisor.to_param, :supervisor => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested supervisor" do
      supervisor = Supervisor.create! valid_attributes
      expect {
        delete :destroy, {:id => supervisor.to_param}, valid_session
      }.to change(Supervisor, :count).by(-1)
    end

    it "redirects to the supervisors list" do
      supervisor = Supervisor.create! valid_attributes
      delete :destroy, {:id => supervisor.to_param}, valid_session
      expect(response).to redirect_to(supervisors_url)
    end
  end

end
